### PR TITLE
Add rejected column and blockers

### PR DESCRIPTION
**Pull request by hellobart**
[Finishes #169836792]

### CODE REVIEW

**Comment by jobn** [comment]
hello :)
this seems interesting. may I ask what the motivation for closing the pr was?

**Comment by hellobart** [comment]
Hey @jobn I would first like to thank you for the Braid! It is really helpful in our daily stand ups!
I've rejected the PR as i misclick target branch (wanted to do PR to our Braid fork).

**Comment by jobn** [comment]
thanks. Any reason why it could not go into braid master?

**Comment by hellobart** [comment]
Well it could go there if you want. I was not really sure whether you need these features (rejected column and links to blockers).

**Comment by hellobart** [comment]
Also, i struggle a bit with getting a blockers story id's. Quick solution was to get story id from  `description` (`const matchStoryId = str => (str && str.match(/([0-9]){9}$/)[0]) || 'Unknown';`). Im not really happy with it as this value can be a `@user`. 
Anyway, blockers model in pivotal api is a bit poor.

**Comment by jobn** [comment]
if you reopen the pull request i can help you out, and maybe we can get it into master.

**Pull request closed without merging**
